import { Injectable, NestMiddleware } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { NextFunction, Request, Response } from "express";
import { RequestContextService } from "./request-context.service";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const HEADER = "x-request-id";

/**
 * The first middleware in the chain. For every request:
 *
 *   1. If the inbound `X-Request-Id` header is present AND has UUID
 *      shape, honour it (allows upstream proxies + load balancers to
 *      pre-assign an id and have it threaded through audit + logs).
 *   2. Otherwise mint a fresh UUID v4.
 *   3. Echo the value back on the response so the client / proxy can
 *      surface it in errors and correlate with our logs.
 *   4. Open an ALS scope so every downstream service can read the id
 *      via `RequestContextService.getRequestId()` without parameter
 *      threading.
 *
 * The UUID-shape gate on inbound is a security guard: without it an
 * attacker could inject arbitrary strings into log aggregation /
 * `audit_log.request_id`, polluting the corpus and slipping past
 * SIEM rule matching.
 *
 * Must run BEFORE `TenantContextMiddleware` so that JWT-verification
 * failures (which take the durable-audit path) still carry a
 * request_id.
 */
@Injectable()
export class RequestContextMiddleware implements NestMiddleware {
  constructor(private readonly requestContext: RequestContextService) {}

  use(req: Request, res: Response, next: NextFunction): void {
    const inbound = req.header(HEADER);
    const requestId = inbound && UUID_RE.test(inbound) ? inbound : randomUUID();

    // Stash on the Express request so `@Req()` consumers can read it
    // without injecting the service. Also lets pino-http use it via
    // genReqId.
    req.requestId = requestId;

    // Echo on the response. Set early so even responses generated by
    // middleware further down the chain (rejected by a guard, thrown by
    // a filter) carry the header.
    res.setHeader("X-Request-Id", requestId);

    this.requestContext.run({ requestId }, () => next());
  }
}
